name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO111MODULE: "on"

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - ~1.21
          - ~1.22
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Get dependencies
        run:  go mod download
      - name: Build
        run:  go build -v .
      - name: Test
        run:  go test -v ./...
